### PR TITLE
Exception added for running shell commands without exit:

### PR DESCRIPTION
**Pull request by daubmannus**
if string begins with '!' it runs in shell.

(Sorry, if you find it's dirty. I'm just missing this feature a lot.)

### CODE REVIEW

**Comment by pvdb** [comment]
Can you post an example of how you'd use this feature, @daubmannus?

**Comment by daubmannus** [comment]
@pvdb it's like in vim or many more unix utils, you work with repl commands and then accidentally need to run shell command.
`git>!ls`
`file.1 file.2 file.3`
`git>add file.3`

**Comment by pvdb** [comment]
Thanks for clarifying, @daubmannus, I understand now.  👍 

But I don't think you actually need to build the behaviour explicitly into `repl` itself, right?

If you want to escape to your shell without exiting `repl`, you can just hit `CTRL-Z` _(which moves `repl` to the background, and runs your shell in the foreground)_, do whatever you need to do in your shell environment, and - once you're done - use your shell's `fg` built-in to return to the running `repl` session:

```
the_rock@mac > repl git
git>> status --short
 M bin/repl
git>> ^Z
[1]+  Stopped                 repl git
the_rock@mac > pwd
/Users/the_rock/Workarea/repl
the_rock@mac > ls -1
LICENSE
README.md
Rakefile
bin
lib
man
repl.gemspec
tags
the_rock@mac > fg
repl git
git>> add bin/repl
git>> status --short
M  bin/repl
git>> ^D
the_rock@mac > _
```

The additional benefit is that you can run multiple commands in your shell environment before returning to your `repl` session, instead of having to repeatedly use the `!` prefix.

**Comment by daubmannus** [comment]
Thank you for the answer, @pvdb
Your solution is fine except the case if I need to change directory and get this new working directory inside repl.
For using repl with git it's really not the big issue, but git is not the only, and for another program I'm working with it's essential.

**Comment by pvdb** [comment]
Thanks for the clarification, @daubmannus 

> Your solution is fine except the case if I need to change directory and get this new working directory inside repl.

Changing the working directory for a running process is not possible, right, not even with your patch, unless I'm missing something?  Only the running `repl` process itself would be able to change its working directory.

Escaping to a shell and changing the working directory would only change it for the subprocess, but as soon as you're back in the `repl` parent process, the working directory would be back to where you started `repl` from:

```
the_rock@mac$ pwd -L
/Users/the_rock/misc/repl
the_rock@mac$ repl /bin/pwd
/bin/pwd>> -L
/Users/the_rock/misc/repl
/bin/pwd>> !cd /tmp && pwd
/tmp
/bin/pwd>> -L
/Users/the_rock/misc/repl
/bin/pwd>> ^D
the_rock@mac$ _
```

**Comment by daubmannus** [comment]
Thank you, @@pvdb
You're absolutely right. My patch seems to be useless.
Should I do something about it? (I'm new to github.)

**Comment by pvdb** [comment]
> You're absolutely right. My patch seems to be useless.

I wouldn't go that far... at the very least it sparked an interesting discussion!

> Should I do something about it? (I'm new to github.)

You can close it, which tidies things up a bit ... just look for the "Close pull request" button at the bottom of the main PR page.

**Pull request closed without merging**
